pki-io/admin

.travis.yml
Makefile

perhaps we will need to revisit this.
The build is passing though

Simplistic Travis.yml

---

.travis.yml
Makefile

After discussing with kalloc I played around a bit (OK, a *lot*) to get things gom compliant. They are not 100% complete yet but this is a step in the right direction.
If course the build passes TravisCI

Fixed Makefile to work with gom

---

.travis.yml
Makefile

Apologies for the poor quality of the commit comments - I thought they would NOT be propagated, given that I worked on a separate branch (mercurial style). Anyway does what it says on the tin, bats testing is enabled.

Enabled bats tests in .travis.yml

---

.travis.yml
Makefile

default needs to be at the top

fixing default

---

.travis.yml
Makefile
pki.io.go
runNode.go
runOrg.go
runPairingKey.go

Its a bit of a mess still. I keep mentally flipping between the CLI being an offline tool and the CLI being a prototype for how the API will work. The idea is to support an offline mode even when the API works, so it will probably just be a nice wrapper around the API functions.
* Closed previous PR because it came from my master
* Interesting to note that gom install doesn't update what is already installed. This meant I was working with my old copy of the pki.io packages. I deleted _vendor and gom install'ed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/41)

Registration flow

---

pki.io.go
runCA.go
runInit.go
runNode.go
runOrg.go
runPairingKey.go

Merged in the logger changes. Split the docopt usages into a main one plus sub-helps for each command.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/47)

Cli refactor

---

pki.io.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/52)

added default logging config and did some minor cleanup.

---

Makefile
bats_tests/01_version.bats
bats_tests/02_help.bats
bats_tests/90_basic_flow.bats
bats_tests/90_basic_flow_offline.bats
bats_tests/fixtures/basics.bash
bats_tests/fixtures/ca.bash
bats_tests/fixtures/node.bash
bats_tests/fixtures/org.bash
bats_tests/fixtures/pairing_key.bash
runInit.go
runNode.go
runOrg.go
runPairingKey.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/54)

Registration refactor

---

runNode.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/65)

fixes #58 - use cert name in file name

---

Gomfile
Makefile

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/66)

core rename

---

adminApp.go
helpers.go
nodeApp.go
runCA.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/69)

ca and cert expiry args

---

.gitignore
Makefile
adminApp.go
bats_tests/90_basic_flow.bats
nodeApp.go
pki.io.go
runAdmin.go
runInit.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/70)

multi admin

---

Makefile

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/75)

simplified makefile

---

bats_tests/20_ca.bats
bats_tests/20_cert.bats
bats_tests/fixtures/ca.bash
bats_tests/fixtures/cert.bash
pki.io.go
runCA.go
runCert.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/81)

dn scope + standalone certs, closes #80

---

runNode.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/82)

adds ca cert to node cert export. closes #74

---

pki.io.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/83)

logs to stderr

---

adminApp.go
helpers.go
nodeApp.go
pki.io.go
runCA.go
runCert.go
runInit.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/84)

added and using two fatal functions

---

adminApp.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/86)

sets cert name from node

---

bats_tests/30_admin.bats
bats_tests/fixtures/admin.bash
bats_tests/fixtures/basics.bash
runAdmin.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/88)

admin delete, list and tests

---

bats_tests/20_ca.bats
bats_tests/fixtures/ca.bash
runCA.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/92)

ca list and delete

---

bats_tests/20_node.bats
bats_tests/fixtures/node.bash
runNode.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/94)

node delete, list and tests. closes #21

---

Gomfile
helpers.go
logging.go
pki.io.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/96)

works with custom stderr, default config, and loading file. closes #85

---

helpers.go
runAdmin.go
runCA.go
runInit.go
runNode.go
runPairingKey.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/95)

cleaning up help, closes #93

---

.travis.yml
Gomfile
Makefile
Vendors

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/98)

using fdm, fixes #87

---

adminApp.go
bats_tests/10_init.bats
bats_tests/fixtures/basics.bash
helpers.go
runAdmin.go
runInit.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/99)

fixes #97 - multi orgs being broken

---

pki.io.go
version.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/104)

version file, closes #100

---

runAdmin.go
runCA.go
runNode.go
runPairingKey.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/108)

Flush, closes #102

---

bats_tests/fixtures/basics.bash

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/109)

ability to use alternative pki.io command

---

Vendors

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/110)

pinning versions

---

Vendors
adminApp.go
bats_tests/10_init.bats
bats_tests/fixtures/admin.bash
bats_tests/fixtures/basics.bash
bats_tests/fixtures/pairing_key.bash
helpers.go
nodeApp.go
runAdmin.go
runInit.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/114)

adding duplicate key checks, plus test, also logging flush fix

---

version.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/115)

patch version bump

---

runCert.go
runInit.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/118)

user friendly error

---

version.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/119)

version bump

---

Vendors
adminApp.go
bats_tests/20_cert.bats
bats_tests/20_csr.bats
bats_tests/90_basic_flow.bats
bats_tests/fixtures/cert.bash
bats_tests/fixtures/csr.bash
pki.io.go
runCA.go
runCSR.go
runCert.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/120)

cert import plus other funcs

---

nodeApp.go
runCSR.go
version.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/123)

CSRs have CNs that can be ignored

---

bats_tests/20_ca.bats
bats_tests/fixtures/ca.bash
runCA.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/124)

docopt mission options meant it ignored --cert and --key

---

runCA.go
runCSR.go
runCert.go
version.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/127)

ability to select keytype

---

bats_tests/90_basic_flow.bats
bats_tests/fixtures/node.bash
bats_tests/fixtures/pairing_key.bash
runNode.go
version.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/129)

fixing node cert, closes pki-io/pki-io/issues/9

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/130)

Added Golang Support 1.5.1 for Travis CI

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/132)

reworked travis.yml to eliminate sudo

---

runVersion.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/135)

should be on 3

---

Vendors
admincontroller.go
bats_tests/fixtures/admin.bash
bats_tests/fixtures/pairing_key.bash
cacontroller.go
certcontroller.go
csrcontroller.go
environment.go
nodecontroller.go
orgcontroller.go
pairingkeycontroler.go
runAdmin.go
runCA.go
runCSR.go
runCert.go
runInit.go
runNode.go
runOrg.go
runPairingKey.go

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pki-io/admin/137)

better view separation and tables
